name: compile

on: 
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm -g install @angular/cli
      - run: ng build
      - run: sed -i 's+<base href="/">+<base href="/Dzialajacy-dziennik-UI/">+g' ./docs/index.html
